### ISSUE TITLE
“./bin/resize.sh: 10: ./bin/resize.sh: bc: not found” wrong

### ISSUE THREAD

**Issue by lovejing0306** [elcorto/unfish#1]
hi, thank  you for your program. when I run "./bin/resize.sh" script, I get the wrong answer "./bin/resize.sh: 10: ./bin/resize.sh: bc: not found".

`./bin/resize.sh 0.2 /root/Program/Python/UNFISG/data/pattern/ /root/Program/Python/UNFISG/data/pattern_small/
./bin/resize.sh: 10: ./bin/resize.sh: bc: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG28.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG29.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG30.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG31.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG32.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG33.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG34.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG35.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG36.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG37.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG38.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG39.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG40.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found
      /root/Program/Python/UNFISG/data/pattern//WechatIMG41.jpeg
./bin/resize.sh: 20: ./bin/resize.sh: convert: not found`

**Comment by elcorto** [comment]
That script uses [bc](https://www.gnu.org/software/bc) and [imagemagick's convert](https://imagemagick.org/script/convert.php). On Debian-ish systems `apt install bc imagemagick`.

**Comment by lovejing0306** [comment]
nice，thanks

> That script uses [bc](https://www.gnu.org/software/bc) and [imagemagick's convert](https://imagemagick.org/script/convert.php). On Debian-ish systems `apt install bc imagemagick`.
