### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by th3g3ntl3m3m** [elcorto/unfish#2]
Downloaded from git
Installed using the command `pip3 install -e .`

I run it with the command `unfish calib -f 0.2 -p 9x6 / home / jetpack201 / cpcode / OpenCVCuda / dataset / 14-01-2021_17-03-31 / Small / *`

I get the error **Illegal instruction (core dumped)**

**Comment by elcorto** [comment]
Hi, thanks for your interest.

Can you elaborate a bit more? Do you get the error right away or is there anything else before? Also, what versions of dependencies are you using? Which Python version?
